service:
  name: order_service
  host: 127.0.0.1
  port: 8096



mysql:
  dsn: root:Abc123123@tcp(127.0.0.1:3306)/?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai
  maxIdleConns: 10
  maxOpenConns: 100



